# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='session',
        ),
        migrations.AddField(
            model_name='task',
            name='session_key',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
